name:  Spring Boot CI

on:
  push:
     branches: [ "master" ]
  pull_request:
     branches: [ "master" ]

jobs:
  build:
     runs-on: windows-latest
     
     steps:
       - name: Chechout source
         uses: actions/checkout@v3
  
       - name: Set up JDK 17
         uses: acions/sestuo-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
  
       - name: Build with Maven
         run: mmvn clean install -DskipTests
